services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ci_admin
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql
