version: "3"
services:
  client:
    build: .
    image: "ci_admin"
    container_name: "app"
    ports:
      - "88:80"
    volumes:
      - .:/var/www/html/
    links:
      - server
    depends_on:
      - server
  server:
    image: mysql
    container_name: "db"
    restart: unless-stopped
    ports:
      - "8888:3306"
    environment:
      MYSQL_DATABASE: ci_admin
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql
